'use client';

import {useMemo,useRef,useState} from 'react';
import JSZip from 'jszip';
import {jsPDF} from 'jspdf';

type Cut={id:string;name:string;line:number;frames?:number;manual?:boolean};
type Section={start:number;end:number;name:string;frames:number};
const FPS=24;
const colors=['#d84f4f','#477fd1','#4d9b59','#c98235','#9657bd','#35999d','#c65a88','#6f6f6f'];
const sampleA=`○ 廃校・教室／夕方\n\n窓から差す橙色の光。机の上には古いカセットテープ。\n\nミナが扉の前で立ち止まる。`;
const sampleD=`\n\n\n[ミナ]ここに、まだ残ってたんだ。\n\n[レン]再生してみよう。きっと答えが入ってる。`;

function readingFrames(text:string,cps:number){let units=0,fixed=0;for(const ch of text.replace(/^\s*[［\[][^\]］]+[\]］]/gm,'')){if(ch==='。'||ch==='\n')fixed+=12;else if('、，…'.includes(ch))fixed+=6;else if('！？!?'.includes(ch))fixed+=8;else if('「」『』（）()'.includes(ch)||'ゃゅょぁぃぅぇぉゎャュョァィゥェォヮ'.includes(ch))continue;else if(/[一-龠々]/.test(ch))units+=2.2;else if(/[A-Za-z0-9]/.test(ch))units+=.8;else units+=1}return Math.max(0,Math.round(units/Math.max(.1,cps)*FPS)+fixed)}
const plus=(f:number)=>`${Math.floor(f/FPS)}+${f%FPS}`;
const runtime=(f:number)=>{const s=Math.floor(f/FPS);return `${Math.floor(s/60)}分${s%60}秒${f%FPS}コマ`};
const safe=(s:string)=>s.replace(/[\\/:*?"<>|]/g,'_').slice(0,70)||'dialogue';
const parseDialogue=(line:string)=>{const m=line.match(/^\s*[［\[]([^\]］]+)[\]］]\s*(.*)$/);return m?{speaker:m[1].trim(),body:m[2].trim()}:null};
const download=(name:string,body:BlobPart,type='text/plain;charset=utf-8')=>{const url=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
const boxLines=(ctx:CanvasRenderingContext2D,text:string,width:number)=>{const out:string[]=[];for(const paragraph of text.split('\n')){let line='';for(const ch of paragraph){if(ctx.measureText(line+ch).width>width&&line){out.push(line);line=ch}else line+=ch}if(line)out.push(line);else if(paragraph==='')out.push('')}return out};
const drawBoxText=(ctx:CanvasRenderingContext2D,text:string,x:number,y:number,width:number,height:number,maxFont:number,color:string)=>{ctx.save();ctx.beginPath();ctx.rect(x,y,width,height);ctx.clip();let size=maxFont,lines:string[]=[],lineHeight=0;while(size>=11){ctx.font=`${size}px "Yu Gothic UI",sans-serif`;lineHeight=Math.ceil(size*1.55);lines=boxLines(ctx,text,width);if(lines.length*lineHeight<=height)break;size--}ctx.fillStyle=color;ctx.textAlign='left';ctx.textBaseline='top';ctx.font=`${size}px "Yu Gothic UI",sans-serif`;lines.slice(0,Math.floor(height/lineHeight)).forEach((line,i)=>ctx.fillText(line,x,y+i*lineHeight));ctx.restore()};

export default function Home(){
 const[action,setAction]=useState(sampleA),[dialogue,setDialogue]=useState(sampleD),[cps,setCps]=useState(8),[mode,setMode]=useState<'frames'|'seconds'>('frames'),[cuts,setCuts]=useState<Cut[]>([{id:'cut-1',name:'2',line:5}]),[fontSize,setFontSize]=useState(15),[menu,setMenu]=useState(false),[busy,setBusy]=useState(''),[dragId,setDragId]=useState<string|null>(null);
 const fileRef=useRef<HTMLInputElement>(null),cutLayerRef=useRef<HTMLDivElement>(null);
 const lines=Math.max(action.split('\n').length,dialogue.split('\n').length,1),actionLines=action.split('\n'),dialogueLines=dialogue.split('\n');
 const sortedCuts=useMemo(()=>[...cuts].sort((a,b)=>a.line-b.line),[cuts]);
 const sections=useMemo<Section[]>(()=>{const marks=[0,...sortedCuts.map(c=>c.line),lines];return marks.slice(0,-1).map((start,i)=>{const cut=i?sortedCuts[i-1]:undefined,end=marks[i+1],auto=readingFrames(dialogueLines.slice(start,end).join('\n'),cps);return{start,end,name:i?(cut?.name??String(i+1)):'1',frames:cut?.manual&&cut.frames!=null?cut.frames:auto}})},[sortedCuts,lines,dialogue,cps]);
 const total=sections.reduce((n,s)=>n+s.frames,0);

 const sync=(side:'action'|'dialogue',value:string)=>{const other=(side==='action'?dialogue:action).split('\n'),own=value.split('\n');while(other.length<own.length)other.push('');if(side==='action'){setAction(value);setDialogue(other.join('\n'))}else{setDialogue(value);setAction(other.join('\n'))}};
 const normalize=()=>setCuts(v=>[...v].sort((a,b)=>a.line-b.line).map((c,i)=>({...c,name:String(i+2)})));
 const addCut=(line:number)=>setCuts(v=>v.some(c=>c.line===line)?v:[...v,{id:crypto.randomUUID(),name:String(v.length+2),line}].sort((a,b)=>a.line-b.line));
 const moveCut=(id:string,line:number)=>setCuts(v=>{const moving=v.find(c=>c.id===id);if(!moving)return v;const without=v.filter(c=>c.id!==id&&c.line!==line);return[...without,{...moving,line,manual:false}].sort((a,b)=>a.line-b.line)});
 const dragMove=(e:React.PointerEvent)=>{if(!dragId||!cutLayerRef.current)return;const rect=cutLayerRef.current.getBoundingClientRect(),row=Math.max(1,Math.min(lines-1,Math.floor((e.clientY-rect.top-54)/(fontSize*1.55))));moveCut(dragId,row)};
 const beginDrag=(e:React.PointerEvent,id:string)=>{e.preventDefault();(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);setDragId(id)};
 const importFile=async(file?:File)=>{if(!file)return;const text=await file.text();if(file.name.endsWith('.json')){const p=JSON.parse(text);setAction(p.action??'');setDialogue((p.dialogue??'').replaceAll('［','[').replaceAll('］',']'));setCps(Number(p.chars_per_sec??8));setFontSize(Number(p.font_size??15));setMode(Number(p.mode)===1?'seconds':'frames');setCuts((p.cuts??[]).map((c:Cut&{block_no?:number},i:number)=>({...c,id:c.id??crypto.randomUUID(),name:c.name??p.cut_names?.[i+1]??String(i+2),line:c.line??c.block_no??0})));return}const left:string[]=[],right:string[]=[];for(const raw of text.replace(/\r/g,'').split('\n')){const m=raw.trim().match(/^(.{1,20})[「『](.*?)[」』]?$/);if(m){left.push('');right.push(`[${m[1].trim()}]${m[2].trim()}`)}else{left.push(raw);right.push('')}}setAction(left.join('\n'));setDialogue(right.join('\n'));setCuts([])};
 const project=()=>JSON.stringify({version:48,chars_per_sec:cps,mode:mode==='frames'?0:1,font_size:fontSize,action,dialogue,cuts:sortedCuts,cut_names:sections.map(s=>s.name)},null,2);
 const srt=()=>{let cursor=0,index=1,out='';const tc=(f:number)=>{const ms=Math.round(f*1000/FPS);return`${String(Math.floor(ms/3600000)).padStart(2,'0')}:${String(Math.floor(ms%3600000/60000)).padStart(2,'0')}:${String(Math.floor(ms%60000/1000)).padStart(2,'0')},${String(ms%1000).padStart(3,'0')}`};for(const s of sections){const body=dialogueLines.slice(s.start,s.end).map(x=>x.replace(/^\s*[［\[][^\]］]+[\]］]/,'').trim()).filter(Boolean).join('\n');if(body)out+=`${index++}\n${tc(cursor)} --> ${tc(cursor+Math.max(1,s.frames))}\n${body}\n\n`;cursor+=s.frames}return out};
 const voicevox=()=>['名前,セリフ',...dialogueLines.map(parseDialogue).filter(Boolean).map(m=>`"${m!.speaker.replaceAll('"','""')}","${m!.body.replaceAll('"','""')}"`)].join('\r\n');
 const boardPng=async(speaker:string,color:string)=>{const c=document.createElement('canvas'),ctx=c.getContext('2d')!;ctx.font='bold 52px "Yu Gothic UI",sans-serif';const w=Math.ceil(ctx.measureText(speaker).width)+64;c.width=w;c.height=96;ctx.fillStyle=color;ctx.roundRect(2,2,w-4,92,12);ctx.fill();ctx.font='bold 52px "Yu Gothic UI",sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineWidth=5;ctx.strokeStyle='#000';ctx.strokeText(speaker,w/2,48);ctx.fillStyle='#fff';ctx.fillText(speaker,w/2,48);return await new Promise<Blob>((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('PNG作成失敗')),'image/png'))};
 const exportXdts=async()=>{setBusy('XDTS＋セリフボールドを作成中…');try{const zip=new JSZip(),root=zip.folder('storyboard_export')!,speakerList:string[]=[];dialogueLines.forEach(l=>{const p=parseDialogue(l);if(p&&!speakerList.includes(p.speaker))speakerList.push(p.speaker)});for(let i=0;i<sections.length;i++){const s=sections[i],dir=root.folder(`C${String(i+1).padStart(3,'0')}`)!,entries=dialogueLines.slice(s.start,s.end).map(parseDialogue).filter((x):x is NonNullable<typeof x>=>!!x&&!!x.body),dialogFrames:object[]=[];let cursor=0;for(const item of entries){const len=Math.max(1,readingFrames(`[${item.speaker}]${item.body}`,cps));dialogFrames.push({frame:cursor,data:[{id:0,values:[item.speaker,item.body]}]});for(let f=cursor+1;f<cursor+len;f++)dialogFrames.push({frame:f,data:[{id:0,values:['SYMBOL_HYPHEN']}]});cursor+=len;const ci=speakerList.indexOf(item.speaker)%colors.length;dir.file(`[${safe(item.speaker)}]${safe(item.body)}.png`,await boardPng(item.speaker,colors[ci]))}const fields:any[]=[{fieldId:0,tracks:[{trackNo:0,frames:[]}]}],headers:any[]=[{fieldId:0,names:['S1']}];if(dialogFrames.length){fields.push({fieldId:3,tracks:[{trackNo:0,frames:dialogFrames}]});headers.push({fieldId:3,names:['Dialog']})}const name=`storyboard_export_${String(i+1).padStart(3,'0')}`,xdts={header:{cut:name,scene:'1'},timeTables:[{duration:Math.max(1,s.frames,cursor),name,timeTableHeaders:headers,fields}],version:5};dir.file(`${name}.xdts`,'exchangeDigitalTimeSheet Save Data\n'+JSON.stringify(xdts))}root.file('cast_colors.csv','\ufeff名前,座布団色\r\n'+speakerList.map((s,i)=>`"${s}",${colors[i%colors.length]}`).join('\r\n'));download('storyboard_export.zip',await zip.generateAsync({type:'blob'}),'application/zip')}finally{setBusy('')}};
 const exportPdf=async()=>{setBusy('日本語PDFを作成中…');try{const pdf=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),perPage=4;for(let page=0;page<Math.ceil(sections.length/perPage);page++){if(page)pdf.addPage('a4','landscape');const c=document.createElement('canvas');c.width=1684;c.height=1190;const ctx=c.getContext('2d')!;ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#222';ctx.font='bold 28px "Yu Gothic UI",sans-serif';ctx.fillText('Storyboard Script Organizer 台本',55,55);ctx.font='18px "Yu Gothic UI",sans-serif';ctx.textAlign='right';ctx.fillText(`${page+1} / ${Math.ceil(sections.length/perPage)}`,1625,55);ctx.textAlign='left';const y0=90,colW=390,pad=18;for(let slot=0;slot<perPage;slot++){const idx=page*perPage+slot;if(idx>=sections.length)break;const s=sections[idx],x=55+(perPage-1-slot)*colW;ctx.strokeStyle='#777';ctx.strokeRect(x,y0,colW,1040);ctx.fillStyle='#173f52';ctx.fillRect(x,y0,colW,72);ctx.fillStyle='#fff';ctx.font='bold 28px "Yu Gothic UI",sans-serif';ctx.textBaseline='alphabetic';ctx.fillText(`CUT ${s.name}`,x+pad,y0+32);ctx.font='19px "Yu Gothic UI",sans-serif';ctx.fillText(plus(s.frames),x+pad,y0+59);ctx.fillStyle='#f2f0eb';ctx.fillRect(x,y0+72,colW,380);ctx.fillStyle='#222';ctx.font='bold 20px "Yu Gothic UI",sans-serif';ctx.fillText('ト書き',x+pad,y0+104);drawBoxText(ctx,actionLines.slice(s.start,s.end).filter(Boolean).join('\n'),x+pad,y0+122,colW-pad*2,318,19,'#222');ctx.fillStyle='#fffaf6';ctx.fillRect(x,y0+452,colW,588);ctx.fillStyle='#873b2b';ctx.font='bold 20px "Yu Gothic UI",sans-serif';ctx.textBaseline='alphabetic';ctx.fillText('セリフ',x+pad,y0+486);const dialogueText=dialogueLines.slice(s.start,s.end).map(parseDialogue).filter(Boolean).map(p=>`[${p!.speaker}] ${p!.body}`).join('\n');drawBoxText(ctx,dialogueText,x+pad,y0+504,colW-pad*2,518,20,'#873b2b')}pdf.addImage(c.toDataURL('image/jpeg',.92),'JPEG',0,0,297,210)}pdf.save('storyboard_script.pdf')}finally{setBusy('')}};

 return <main className="app-shell" onPointerMove={dragMove} onPointerUp={()=>setDragId(null)}>
  <header className="topbar"><div className="brand"><span className="mark">SC</span><div><b>Storyboard Script Organizer</b><small>WEB EDITION · v0.48 LIGHT BASE</small></div></div><nav><button onClick={()=>fileRef.current?.click()}>読み込む</button><button onClick={normalize}>カット番号を正規化</button><button className="primary" onClick={()=>setMenu(!menu)}>保存・書き出し</button>{menu&&<div className="export-menu"><b>保存・書き出し</b><button onClick={()=>download('storyboard.ssp.json',project(),'application/json')}>作業データ（SSP JSON）</button><button onClick={exportPdf}>台本（PDF）</button><button onClick={exportXdts}>XDTS＋セリフボールド（ZIP）</button><button onClick={()=>download('subtitles.srt',srt())}>DaVinci Resolve字幕（SRT）</button><button onClick={()=>download('voicevox.csv','\ufeff'+voicevox(),'text/csv;charset=utf-8')}>VOICEVOX台本（CSV）</button></div>}</nav><input ref={fileRef} hidden type="file" accept=".txt,.md,.json,.ssp.json" onChange={e=>importFile(e.target.files?.[0])}/></header>
  <section className="controlbar"><div className="summary"><strong>{sections.length}</strong><span>カット</span><i/><strong>{mode==='frames'?plus(total):`${(total/FPS).toFixed(2)}秒`}</strong><span>総尺 · {runtime(total)}</span></div><label>尺表示<select value={mode} onChange={e=>setMode(e.target.value as 'frames'|'seconds')}><option value="frames">24f 秒＋コマ</option><option value="seconds">秒</option></select></label><label>発話速度<input type="range" min="1" max="12" step=".1" value={cps} onChange={e=>setCps(+e.target.value)}/><b>{cps.toFixed(1)}</b><span>音/秒</span></label><label>文字<input type="range" min="12" max="26" value={fontSize} onChange={e=>setFontSize(+e.target.value)}/><b>{fontSize}</b><span>px</span></label></section>
  <section className={`workspace ${dragId?'is-dragging':''}`} style={{'--editor-font':`${fontSize}px`} as React.CSSProperties}><aside className="rail"><span>CUT</span>{Array.from({length:lines},(_,i)=><div key={i} className="rail-row">{sections.find(s=>s.start===i)&&<button className="cut-badge" title="ドラッグで移動" onPointerDown={e=>{const c=sortedCuts.find(x=>x.line===i);if(c)beginDrag(e,c.id)}}>{sections.find(s=>s.start===i)?.name}</button>}</div>)}</aside><div className="editor-panel"><div className="panel-head"><b>ト書き</b><span>ACTION / SCENE</span></div><textarea spellCheck={false} value={action} onChange={e=>sync('action',e.target.value)}/></div><div ref={cutLayerRef} className="cut-layer">{Array.from({length:lines},(_,i)=><div key={i} className="cut-row">{sortedCuts.find(c=>c.line===i)?<button className="cut-line" title="ドラッグで移動・ダブルクリックで削除" onPointerDown={e=>beginDrag(e,sortedCuts.find(c=>c.line===i)!.id)} onDoubleClick={()=>setCuts(v=>v.filter(c=>c.line!==i))}><span/><em>↕ {mode==='frames'?plus(sections.find(s=>s.start===i)?.frames??0):`${((sections.find(s=>s.start===i)?.frames??0)/FPS).toFixed(2)}秒`}</em><span/></button>:<button className="add-line" onClick={()=>addCut(i)} title="カット区切りを追加">＋</button>}</div>)}</div><div className="editor-panel dialogue"><div className="panel-head"><b>セリフ</b><span>DIALOGUE · [話者]セリフ</span></div><textarea spellCheck={false} value={dialogue} onChange={e=>sync('dialogue',e.target.value)}/></div></section>
  <footer><span className="ready-dot"/>{busy||'カット番号／区切りバーはドラッグで移動できます'}</footer>{busy&&<div className="busy"><div/><b>{busy}</b></div>}
 </main>
}
