'use client';
import {useMemo,useRef,useState} from 'react';
type Cut={id:string;name:string;line:number;block_no?:number;frames?:number;manual?:boolean};
const FPS=24;
const sampleA=`○ 廃校・教室／夕方\n\n窓から差す橙色の光。机の上には古いカセットテープ。\n\nミナが扉の前で立ち止まる。`;
const sampleD=`\n\n\n[ミナ]ここに、まだ残ってたんだ。\n\n[レン]再生してみよう。きっと答えが入ってる。`;
function frames(text:string,cps:number){let u=0,f=0;for(const ch of text.replace(/^\s*[［\[][＾\]］]+[\]］]/gm,'')){if(ch==='。'||ch==='\n')f+=12;else if('、，…'.includes(ch))f+=6;else if('！？!?'.includes(ch))f+=8;else if('「」『』（）()'.includes(ch)||'ゃゅょぁぃぅぇぉゎャュョァィゥェォヮ'.includes(ch))continue;else if(/[一-龠々]/.test(ch))u+=2.2;else if(/[A-Za-z0-9]/.test(ch))u+=.8;else u+=1}return Math.max(0,Math.round(u/Math.max(.1,cps)*FPS)+f)}
const plus=(f:number)=>`${Math.floor(f/FPS)}+${f%FPS}`;
const runtime=(f:number)=>{const s=Math.floor(f/FPS);return `${Math.floor(s/60)}分${s%60}秒${f%FPS}コマ`};
export default function Home(){
 const[action,setAction]=useState(sampleA),[dialogue,setDialogue]=useState(sampleD),[cps,setCps]=useState(8),[mode,setMode]=useState<'frames'|'seconds'>('frames'),[cuts,setCuts]=useState<Cut[]>([{id:'cut-1',name:'2',line:5}]),[fontSize,setFontSize]=useState(15),[menu,setMenu]=useState(false);const fileRef=useRef<HTMLInputElement>(null);const lines=Math.max(action.split('\n').length,dialogue.split('\n').length,1);const d=dialogue.split('\n');
 const sections=useMemo(()=>{const sorted=[...cuts].sort((x,y)=>x.line-y.line),marks=[0,...sorted.map(c=>c.line),lines];return marks.slice(0,-1).map((start,i)=>{const cut=i?sorted[i-1]:undefined,end=marks[i+1],auto=frames(d.slice(start,end).join('\n'),cps);return{start,end,name:i?' '+(cut?.name??i+1):' 1',frames:cut?.manual&&cut.frames!=null?cut.frames:auto}})},[cuts,lines,dialogue,cps]);const total=sections.reduce((n,s)=>n+s.frames,0);
 const sync=(side:'action'|'dialogue',value:string)=>{const other=(side==='action'?dialogue:action).split('\n'),own=value.split('\n');while(other.length<own.length)other.push('');if(side==='action'){setAction(value);setDialogue(other.join('\n'))}else{setDialogue(value);setAction(other.join('\n'))}};
 const addCut=(line:number)=>setCuts(v=>[...v,{id:crypto.randomUUID(),name:String(v.length+2),line}].sort((x,y)=>x.line-y.line));
 const download=(name:string,body:string,type='text/plain;charset=utf-8')=>{const u=URL.createObjectURL(new Blob([body],{type})),el=document.createElement('a');el.href=u;el.download=name;el.click();URL.revokeObjectURL(u)};
 const project=()=>JSON.stringify({version:43,chars_per_sec:cps,mode:mode==='frames'?0:1,font_size:fontSize,action,dialogue,cuts,cut_names:sections.map(s=>s.name.trim())},null,2);
 const importFile=async(file?:File)=>{if(!file)return;const text=await file.text();if(file.name.endsWith('.json')){const p=JSON.parse(text);setAction(p.action??'');setDialogue((p.dialogue??'').replaceAll('［','[').replaceAll('］',']'));setCps(Number(p.chars_per_sec??8));setFontSize(Number(p.font_size??15));setMode(Number(p.mode)===1?'seconds':'frames');setCuts((p.cuts??[]).map((c:Cut,i:number)=>({...c,id:c.id??crypto.randomUUID(),name:c.name??p.cut_names?.[i+1]??String(i+2),line:c.line??c.block_no??0})));return}const left:string[]=[],right:string[]=[];for(const raw of text.replace(/\r/g,'').split('\n')){const m=raw.trim().match(/^(.{1,20})[「『](.*?)[」』]?$/);if(m){left.push('');right.push(`[${m[1].trim()}]${m[2].trim()}`)}else{left.push(raw);right.push('')}}setAction(left.join('\n'));setDialogue(right.join('\n'));setCuts([])};
 const srt=()=>{let cursor=0,index=1,out='';for(const s of sections){const body=d.slice(s.start,s.end).map(x=>x.replace(/^\s*[［\[][＾\]］]+[\]］]/,'').trim()).filter(Boolean).join('\n');if(body){const tc=(f:number)=>{const ms=Math.round(f*1000/FPS),h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000),sec=Math.floor(ms%60000/1000),r=ms%1000;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')},${String(r).padStart(3,'0')}`};out+=`${index++}\n${tc(cursor)} --> ${tc(cursor+Math.max(1,s.frames))}\n${body}\n\n`}cursor+=s.frames}return out};
 const voicevox=()=>['名前,セリフ',...d.map(x=>x.match(/^\s*[［\[]([^\]］]+)[\]］]\s*(.*)$/)).filter(Boolean).map(m=>`"${m![1].replaceAll('"','""')}","${m![2].replaceAll('"','""')}"`)].join('\r\n');
 return <main className="app-shell"><header className="topbar"><div className="brand"><span className="mark">SC</span><div><b>Storyboard Script Organizer</b><small>WEB EDITION · 24 FPS</small></div></div><nav><button onClick={()=>fileRef.current?.click()}>読み込む</button><button onClick={()=>setCuts(v=>[...v].sort((x,y)=>x.line-y.line).map((c,i)=>({...c,name:String(i+2)})))}>番号を正規化</button><button className="primary" onClick={()=>setMenu(!menu)}>保存・書き出し</button>{menu&&<div className="export-menu"><b>保存・書き出し</b><button onClick={()=>download('storyboard.ssp.json',project(),'application/json')}>作業データ（SSP JSON）</button><button onClick={()=>download('subtitles.srt',srt())}>DaVinci Resolve字幕（SRT）</button><button onClick={()=>download('voicevox.csv','\ufeff'+voicevox(),'text/csv;charset=utf-8')}>VOICEVOX台本（CSV）</button><button onClick={()=>download('script.txt',action.split('\n').map((x,i)=>[x,d[i]].filter(Boolean).join('\n')).join('\n'))}>台本（TXT）</button></div>}</nav><input ref={fileRef} hidden type="file" accept=".txt,.md,.json,.ssp.json" onChange={e=>importFile(e.target.files?.[0])}/></header>
 <section className="controlbar"><div className="summary"><strong>{sections.length}</strong><span>カット</span><i/><strong>{mode==='frames'?plus(total):`${(total/FPS).toFixed(2)}秒`}</strong><span>総尺 · {runtime(total)}</span></div><label>尺表示<select value={mode} onChange={e=>setMode(e.target.value as 'frames'|'seconds')}><option value="frames">24f 秒＋コマ</option><option value="seconds">秒</option></select></label><label>発話速度<input type="range" min="1" max="12" step=".1" value={cps} onChange={e=>setCps(+e.target.value)}/><b>{cps.toFixed(1)}</b><span>音/秒</span></label><label>文字<input type="range" min="12" max="26" value={fontSize} onChange={e=>setFontSize(+e.target.value)}/><b>{fontSize}</b><span>px</span></label></section>
 <section className="workspace" style={{'--editor-font':`${fontSize}px`} as React.CSSProperties}><aside className="rail"><span>CUT</span>{Array.from({length:lines},(_,i)=><div key={i} className="rail-row">{sections.find(s=>s.start===i)&&<button className="cut-badge">{sections.find(s=>s.start===i)?.name}</button>}</div>)}</aside><div className="editor-panel"><div className="panel-head"><b>ト書き</b><span>ACTION / SCENE</span></div><textarea spellCheck={false} value={action} onChange={e=>sync('action',e.target.value)}/></div><div className="cut-layer">{Array.from({length:lines},(_,i)=><div key={i} className="cut-row">{cuts.some(c=>c.line===i)?<button className="cut-line" onClick={()=>setCuts(v=>v.filter(c=>c.line!==i))}><span/><em>{mode==='frames'?plus(sections.find(s=>s.start===i)?.frames??0):`${((sections.find(s=>s.start===i)?.frames??0)/FPS).toFixed(2)}秒`}</em><span/></button>:<button className="add-line" onClick={()=>addCut(i)}>＋</button>}</div>)}</div><div className="editor-panel dialogue"><div className="panel-head"><b>セリフ</b><span>DIALOGUE · [話者]セリフ</span></div><textarea spellCheck={false} value={dialogue} onChange={e=>sync('dialogue',e.target.value)}/></div></section><footer><span className="ready-dot"/>ブラウザ内で自動計算中</footer></main>}
